import { GitHubIcon, InstagramIcon, TelegramIcon } from '@/assets/icons/ui'

export const home_data = {
  languages: ['en', 'es', 'ru', 'uk'],
  contacts: [
    {
      id: 0,
      name: 'alexey.bortnytskyi@gmail.com',
      href: 'mailto:alexey.bortnytskyi@gmail.com',
    },
    {
      id: 1,
      name: '34 680 522 262',
      href: 'tel:34680522262',
    },
  ],
  socials: [
    {
      id: 0,
      href: 'https://www.instagram.com/webshark.dev/',
      icon: InstagramIcon,
    },
    {
      id: 1,
      href: 'https://t.me/websharkdev',
      icon: TelegramIcon,
    },
    {
      id: 2,
      href: 'https://github.com/websharkdev',
      icon: GitHubIcon,
    },
  ],
  mail: 'alexey.bortnytskyi@gmail.com',
  cv_link: 'https://www.notion.so/CV-d9f17ad32676467f895a71b48974b6ae',
}

// @ts-ignore
export const myAge = Math.floor((new Date() - new Date('19 Jun 2003')) / (60 * 60 * 24 * 1000 * 365))

export const user_data = {
  fio: '',
  header_fio: 'Bortnytskyi. Alexey',
  logoName: 'webshark.translate',
  menu: [
    {
      id: 0,
      title: 'Home',
      link: '/',
    },
    {
      id: 1,
      title: 'Translate',
      link: '/translate',
    },
    {
      id: 2,
      title: 'Synonyms',
      link: '/synonyms',
    },
  ],
  home_title: 'We open up language to everyone',
  home_buttons: [
    {
      id: 0,
      name: 'Translate',
      href: '/translate',
      className: 'button-primary',
    },
    {
      id: 1,
      name: 'Synonyms',
      href: '/synonyms',
      className: 'button-secondary',
    },
  ],

  translate_languages: [
    'aa',
    'ab',
    'ae',
    'af',
    'ak',
    'am',
    'an',
    'ar',
    'as',
    'av',
    'ay',
    'az',
    'ba',
    'be',
    'bg',
    'bh',
    'bm',
    'bi',
    'bn',
    'bo',
    'br',
    'bs',
    'ca',
    'ce',
    'ch',
    'co',
    'cr',
    'cs',
    'cu',
    'cv',
    'cy',
    'da',
    'de',
    'dv',
    'dz',
    'ee',
    'el',
    'en',
    'eo',
    'es',
    'et',
    'eu',
    'fa',
    'ff',
    'fi',
    'fj',
    'fo',
    'fr',
    'fy',
    'ga',
    'gd',
    'gl',
    'gn',
    'gu',
    'gv',
    'ha',
    'he',
    'hi',
    'ho',
    'hr',
    'ht',
    'hu',
    'hy',
    'hz',
    'ia',
    'id',
    'ie',
    'ig',
    'ii',
    'ik',
    'io',
    'is',
    'it',
    'iu',
    'ja',
    'jv',
    'ka',
    'kg',
    'ki',
    'kj',
    'kk',
    'kl',
    'km',
    'kn',
    'ko',
    'kr',
    'ks',
    'ku',
    'kv',
    'kw',
    'ky',
    'la',
    'lb',
    'lg',
    'li',
    'ln',
    'lo',
    'lt',
    'lu',
    'lv',
    'mg',
    'mh',
    'mi',
    'mk',
    'ml',
    'mn',
    'mr',
    'ms',
    'mt',
    'my',
    'na',
    'nb',
    'nd',
    'ne',
    'ng',
    'nl',
    'nn',
    'no',
    'nr',
    'nv',
    'ny',
    'oc',
    'oj',
    'om',
    'or',
    'os',
    'pa',
    'pi',
    'pl',
    'ps',
    'pt',
    'qu',
    'rm',
    'rn',
    'ro',
    'ru',
    'rw',
    'sa',
    'sc',
    'sd',
    'se',
    'sg',
    'si',
    'sk',
    'sl',
    'sm',
    'sn',
    'so',
    'sq',
    'sr',
    'ss',
    'st',
    'su',
    'sv',
    'sw',
    'ta',
    'te',
    'tg',
    'th',
    'ti',
    'tk',
    'tl',
    'tn',
    'to',
    'tr',
    'ts',
    'tt',
    'tw',
    'ty',
    'ug',
    'uk',
    'ur',
    'uz',
    've',
    'vi',
    'vo',
    'wa',
    'wo',
    'xh',
    'yi',
    'yo',
    'za',
    'zh',
    'zu',
  ],
}

export const helpUkraineEN = {
  section: 'about',
  images: [
    {
      id: 0,
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Civilian_evacuation_across_Irpin_River_2022-03-08_4.jpg/1280px-Civilian_evacuation_across_Irpin_River_2022-03-08_4.jpg',
      alt: 'Evacuation of residents across the Irpin River',
    },
    {
      id: 1,
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/A_damaged_building_in_Mashtorf.jpg/1280px-A_damaged_building_in_Mashtorf.jpg',
      alt: 'Burnt house in Mashtorf',
    },
    {
      id: 2,
      src: 'https://upload.wikimedia.org/wikipedia/commons/1/10/Transfer_of_civilians_from_Irpin_to_Kyiv_due_to_Russian_attacks.jpg',
      alt: 'Evacuation of civilians from Irpin to Kyiv across the Romanovsky bridge.',
    },
    {
      id: 3,
      src: 'https://img.pravda.com/images/doc/6/d/6d5c838-bd1c7be-fm1ly2uxmaaqt9v.jpg',
      alt: 'Destroid house',
    },
    {
      id: 4,
      src: 'https://gdb.rferl.org/08700000-0a00-0242-d11a-08da043367e7_w1597_n_st.jpg',
      alt: 'Murdored civilian people',
    },
    {
      id: 5,
      src: 'https://gdb.rferl.org/08700000-0a00-0242-218a-08da04336e78_w1597_n_st.jpg',
      alt: 'Murdored civilian people',
    },
    {
      id: 5,
      src: 'https://gdb.rferl.org/08700000-0a00-0242-d1df-08da04336396_w1597_n_st.jpg',
      alt: 'Murdored civilian people',
    },
  ],
  text: [
    {
      id: 0,
      text: `My name is Olexii, I'm a frontend developer from Irpin (city close to Kyiv), Ukraine.`,
    },
    {
      id: 1,
      text: `On 24th of February 2022 I woke up to war: Russian armed forces have invaded my country. Driven by chauvinistic ideals and determination to eradicate the Ukrainian people, this act of aggression can only be described as genocide.`,
    },
    {
      id: 2,
      text: `Russian soldiers spare no thought when bombing residential areas, hospitals, schools, museums, cultural heritages, and civilian infrastructure. The list of committed war crimes grows longer by the minute, while the rest of the world largely remains passive.`,
    },
    {
      id: 3,
      text: `Be on the right side of history! Today it's us, tomorrow it could be you.`,
    },
  ],

  financially: {
    section: 'Help financially.',
    text: 'Please consider helping Ukraine fight back by donating to local charitable funds. Avoid donating to global funds such as Red Cross, UNCR, or other non-UA based NGOs — their support is ineffective.',
    aids: [
      {
        id: 0,
        title: 'united24',
        text: 'Official government donation page.United24 is a global initiative to support Ukraine launched on May 5, 2022 by the Ukrainian authorities during the Russian invasion of Ukraine.',
        image: 'https://via.placeholder.com/880x879.png/a59090/000000?Text=880x879',
        link: {
          id: 0,
          title: 'help.',
          link: '#',
        },
      },
      {
        id: 1,
        title: 'united24',
        text: 'Official government donation page.United24 is a global initiative to support Ukraine launched on May 5, 2022 by the Ukrainian authorities during the Russian invasion of Ukraine.',
        image: 'https://via.placeholder.com/347x179.png/a59090/000000?Text=347x179',
        link: {
          id: 0,
          title: 'help.',
          link: '#',
        },
      },
      {
        id: 2,
        title: 'united24',
        text: 'Official government donation page.United24 is a global initiative to support Ukraine launched on May 5, 2022 by the Ukrainian authorities during the Russian invasion of Ukraine.',
        image: 'https://via.placeholder.com/347x179.png/a59090/000000?Text=347x179',
        link: {
          id: 0,
          title: 'help.',
          link: '#',
        },
      },
      {
        id: 3,
        title: 'united24',
        text: 'Official government donation page.United24 is a global initiative to support Ukraine launched on May 5, 2022 by the Ukrainian authorities during the Russian invasion of Ukraine.',
        image: 'https://via.placeholder.com/347x179.png/a59090/000000?Text=347x179',
        link: {
          id: 0,
          title: 'help.',
          link: '#',
        },
      },
      {
        id: 4,
        title: 'united24',
        text: 'Official government donation page.United24 is a global initiative to support Ukraine launched on May 5, 2022 by the Ukrainian authorities during the Russian invasion of Ukraine.',
        image: 'https://via.placeholder.com/347x179.png/a59090/000000?Text=347x179',
        link: {
          id: 0,
          title: 'help.',
          link: '#',
        },
      },
    ],
  },
}

export const helpUkraineRU = {
  section: 'about',
  images: [
    {
      id: 0,
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Civilian_evacuation_across_Irpin_River_2022-03-08_4.jpg/1280px-Civilian_evacuation_across_Irpin_River_2022-03-08_4.jpg',
      alt: 'Evacuation of residents across the Irpin River',
    },
    {
      id: 1,
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/A_damaged_building_in_Mashtorf.jpg/1280px-A_damaged_building_in_Mashtorf.jpg',
      alt: 'Burnt house in Mashtorf',
    },
    {
      id: 2,
      src: 'https://upload.wikimedia.org/wikipedia/commons/1/10/Transfer_of_civilians_from_Irpin_to_Kyiv_due_to_Russian_attacks.jpg',
      alt: 'Evacuation of civilians from Irpin to Kyiv across the Romanovsky bridge.',
    },
    {
      id: 3,
      src: 'https://img.pravda.com/images/doc/6/d/6d5c838-bd1c7be-fm1ly2uxmaaqt9v.jpg',
      alt: 'Destroid house',
    },
    {
      id: 4,
      src: 'https://gdb.rferl.org/08700000-0a00-0242-d11a-08da043367e7_w1597_n_st.jpg',
      alt: 'Murdored civilian people',
    },
    {
      id: 5,
      src: 'https://gdb.rferl.org/08700000-0a00-0242-218a-08da04336e78_w1597_n_st.jpg',
      alt: 'Murdored civilian people',
    },
    {
      id: 5,
      src: 'https://gdb.rferl.org/08700000-0a00-0242-d1df-08da04336396_w1597_n_st.jpg',
      alt: 'Murdored civilian people',
    },
  ],
  text: [
    {
      id: 0,
      text: `My name is Olexii, I'm a frontend developer from Irpin (city close to Kyiv), Ukraine.`,
    },
    {
      id: 1,
      text: `On 24th of February 2022 I woke up to war: Russian armed forces have invaded my country. Driven by chauvinistic ideals and determination to eradicate the Ukrainian people, this act of aggression can only be described as genocide.`,
    },
    {
      id: 2,
      text: `Russian soldiers spare no thought when bombing residential areas, hospitals, schools, museums, cultural heritages, and civilian infrastructure. The list of committed war crimes grows longer by the minute, while the rest of the world largely remains passive.`,
    },
    {
      id: 3,
      text: `Be on the right side of history! Today it's us, tomorrow it could be you.`,
    },
  ],

  financially: {
    section: 'Help financially.',
    text: 'Please consider helping Ukraine fight back by donating to local charitable funds. Avoid donating to global funds such as Red Cross, UNCR, or other non-UA based NGOs — their support is ineffective.',
    aids: [
      {
        id: 0,
        title: 'united24',
        text: 'Official government donation page.United24 is a global initiative to support Ukraine launched on May 5, 2022 by the Ukrainian authorities during the Russian invasion of Ukraine.',
        image: 'https://via.placeholder.com/880x879.png/a59090/000000?Text=880x879',
        link: {
          id: 0,
          title: 'help.',
          link: '#',
        },
      },
      {
        id: 1,
        title: 'united24',
        text: 'Official government donation page.United24 is a global initiative to support Ukraine launched on May 5, 2022 by the Ukrainian authorities during the Russian invasion of Ukraine.',
        image: 'https://via.placeholder.com/347x179.png/a59090/000000?Text=347x179',
        link: {
          id: 0,
          title: 'help.',
          link: '#',
        },
      },
      {
        id: 2,
        title: 'united24',
        text: 'Official government donation page.United24 is a global initiative to support Ukraine launched on May 5, 2022 by the Ukrainian authorities during the Russian invasion of Ukraine.',
        image: 'https://via.placeholder.com/347x179.png/a59090/000000?Text=347x179',
        link: {
          id: 0,
          title: 'help.',
          link: '#',
        },
      },
      {
        id: 3,
        title: 'united24',
        text: 'Official government donation page.United24 is a global initiative to support Ukraine launched on May 5, 2022 by the Ukrainian authorities during the Russian invasion of Ukraine.',
        image: 'https://via.placeholder.com/347x179.png/a59090/000000?Text=347x179',
        link: {
          id: 0,
          title: 'help.',
          link: '#',
        },
      },
      {
        id: 4,
        title: 'united24',
        text: 'Official government donation page.United24 is a global initiative to support Ukraine launched on May 5, 2022 by the Ukrainian authorities during the Russian invasion of Ukraine.',
        image: 'https://via.placeholder.com/347x179.png/a59090/000000?Text=347x179',
        link: {
          id: 0,
          title: 'help.',
          link: '#',
        },
      },
    ],
  },
}
